// utils/pdfGenerator.js — Professional PDF generation using PDFKit
const PDFDocument = require('pdfkit');

// Color palette
const COLORS = {
  primary:    '#1a1a2e',
  accent:     '#e8a87c',
  accentDark: '#c4845a',
  light:      '#f8f4ef',
  muted:      '#888888',
  white:      '#ffffff',
  border:     '#e0d8cf',
};

/**
 * Draw a colored rectangle (helper).
 */
function rect(doc, x, y, w, h, color) {
  doc.save().rect(x, y, w, h).fill(color).restore();
}

/**
 * Generate a professional PDF for the itinerary.
 * Returns a Buffer containing the PDF data.
 */
function generateItineraryPDF(trip, itinerary) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 0,
      info: {
        Title: `WanderLux — ${itinerary.destination} Itinerary`,
        Author: 'WanderLux AI Travel Planner',
        Subject: `${trip.days}-Day Trip to ${itinerary.destination}`,
      },
    });

    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const PAGE_W = doc.page.width;
    const PAGE_H = doc.page.height;
    const MARGIN = 50;
    const CONTENT_W = PAGE_W - MARGIN * 2;

    // ── Cover Page ────────────────────────────────────────
    rect(doc, 0, 0, PAGE_W, PAGE_H, COLORS.primary);
    rect(doc, 0, PAGE_H - 8, PAGE_W, 8, COLORS.accent);

    // Logo / brand
    doc
      .font('Helvetica-Bold')
      .fontSize(11)
      .fillColor(COLORS.accent)
      .text('WANDERLUX', MARGIN, 55, { letterSpacing: 4 });

    // Decorative line
    doc
      .moveTo(MARGIN, 80)
      .lineTo(MARGIN + 40, 80)
      .strokeColor(COLORS.accent)
      .lineWidth(2)
      .stroke();

    // Destination
    doc
      .font('Helvetica-Bold')
      .fontSize(48)
      .fillColor(COLORS.white)
      .text(itinerary.destination || trip.destination, MARGIN, PAGE_H / 2 - 80, {
        width: CONTENT_W,
        lineGap: 6,
      });

    // Country
    if (itinerary.country) {
      doc
        .font('Helvetica')
        .fontSize(18)
        .fillColor(COLORS.accent)
        .text(itinerary.country, MARGIN, doc.y + 8);
    }

    // Divider
    doc
      .moveTo(MARGIN, doc.y + 20)
      .lineTo(MARGIN + 80, doc.y + 20)
      .strokeColor(COLORS.accent)
      .lineWidth(1.5)
      .stroke();

    // Trip details row
    const detailY = doc.y + 35;
    doc
      .font('Helvetica')
      .fontSize(13)
      .fillColor(COLORS.white)
      .text(`${trip.days} Days  ·  ${trip.destination}`, MARGIN, detailY);

    // Summary
    if (itinerary.summary) {
      doc
        .font('Helvetica')
        .fontSize(11)
        .fillColor('#aaaacc')
        .text(itinerary.summary, MARGIN, doc.y + 20, { width: CONTENT_W - 40, lineGap: 4 });
    }

    // Footer
    const generated = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor(COLORS.muted)
      .text(`Generated by WanderLux AI  ·  ${generated}`, MARGIN, PAGE_H - 50, { width: CONTENT_W });

    // ── Quick Info Page ───────────────────────────────────
    doc.addPage({ margin: 0 });
    rect(doc, 0, 0, PAGE_W, 90, COLORS.primary);

    doc
      .font('Helvetica-Bold')
      .fontSize(10)
      .fillColor(COLORS.accent)
      .text('WANDERLUX', MARGIN, 30, { letterSpacing: 3 });

    doc
      .font('Helvetica-Bold')
      .fontSize(22)
      .fillColor(COLORS.white)
      .text('Trip Overview', MARGIN, 50);

    let y = 115;

    // Quick facts grid
    const facts = [
      { label: 'Destination', value: itinerary.destination || trip.destination },
      { label: 'Duration', value: `${trip.days} Days` },
      { label: 'Best Time', value: itinerary.bestTimeToVisit || '—' },
      { label: 'Currency', value: itinerary.currency || '—' },
      { label: 'Language', value: itinerary.language || '—' },
    ];

    facts.forEach((fact, i) => {
      const col = i % 2;
      const row = Math.floor(i / 2);
      const fx = MARGIN + col * (CONTENT_W / 2 + 10);
      const fy = y + row * 60;

      rect(doc, fx, fy, CONTENT_W / 2 - 10, 48, COLORS.light);
      doc
        .font('Helvetica')
        .fontSize(8)
        .fillColor(COLORS.muted)
        .text(fact.label.toUpperCase(), fx + 12, fy + 10, { letterSpacing: 1 });
      doc
        .font('Helvetica-Bold')
        .fontSize(12)
        .fillColor(COLORS.primary)
        .text(fact.value, fx + 12, fy + 24, { width: CONTENT_W / 2 - 30 });
    });

    y += Math.ceil(facts.length / 2) * 60 + 20;

    // Budget
    if (itinerary.estimatedTotalBudget) {
      doc
        .font('Helvetica-Bold')
        .fontSize(14)
        .fillColor(COLORS.primary)
        .text('Estimated Budget Range', MARGIN, y);

      y = doc.y + 10;
      const budgetItems = [
        { tier: 'Budget', value: itinerary.estimatedTotalBudget.budget },
        { tier: 'Moderate', value: itinerary.estimatedTotalBudget.moderate },
        { tier: 'Luxury', value: itinerary.estimatedTotalBudget.luxury },
      ];
      budgetItems.forEach((b, i) => {
        const bx = MARGIN + i * (CONTENT_W / 3 + 5);
        rect(doc, bx, y, CONTENT_W / 3 - 5, 50, i === 1 ? COLORS.accent : COLORS.light);
        const textColor = i === 1 ? COLORS.white : COLORS.primary;
        doc
          .font('Helvetica')
          .fontSize(8)
          .fillColor(i === 1 ? COLORS.primary : COLORS.muted)
          .text(b.tier.toUpperCase(), bx + 10, y + 10);
        doc
          .font('Helvetica-Bold')
          .fontSize(11)
          .fillColor(textColor)
          .text(b.value || '—', bx + 10, y + 24, { width: CONTENT_W / 3 - 20 });
      });
      y += 70;
    }

    // Transportation
    if (itinerary.transportation) {
      doc
        .font('Helvetica-Bold')
        .fontSize(14)
        .fillColor(COLORS.primary)
        .text('Getting Around', MARGIN, y);
      y = doc.y + 8;

      const trans = itinerary.transportation;
      if (trans.fromAirport) {
        doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.accent).text('Airport Transfer', MARGIN, y);
        y = doc.y + 2;
        doc.font('Helvetica').fontSize(10).fillColor(COLORS.primary).text(trans.fromAirport, MARGIN, y, { width: CONTENT_W });
        y = doc.y + 8;
      }
      if (trans.localTransport) {
        doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.accent).text('Local Transport', MARGIN, y);
        y = doc.y + 2;
        doc.font('Helvetica').fontSize(10).fillColor(COLORS.primary).text(trans.localTransport, MARGIN, y, { width: CONTENT_W });
        y = doc.y + 8;
      }
    }

    // Essential Tips
    if (itinerary.essentialTips && itinerary.essentialTips.length > 0) {
      if (y > PAGE_H - 200) { doc.addPage({ margin: 0 }); y = 60; }

      doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.primary).text('Essential Tips', MARGIN, y);
      y = doc.y + 10;

      itinerary.essentialTips.forEach((tip, i) => {
        rect(doc, MARGIN, y, 6, 6, COLORS.accent);
        doc
          .font('Helvetica')
          .fontSize(10)
          .fillColor(COLORS.primary)
          .text(tip, MARGIN + 16, y - 1, { width: CONTENT_W - 16 });
        y = doc.y + 6;
      });
    }

    // ── Day-by-Day Pages ──────────────────────────────────
    const days = itinerary.days || [];
    days.forEach((day) => {
      doc.addPage({ margin: 0 });

      // Day header bar
      rect(doc, 0, 0, PAGE_W, 75, COLORS.primary);
      rect(doc, PAGE_W - 90, 0, 90, 75, COLORS.accent);

      doc
        .font('Helvetica-Bold')
        .fontSize(10)
        .fillColor(COLORS.accent)
        .text('WANDERLUX', MARGIN, 18, { letterSpacing: 3 });

      doc
        .font('Helvetica-Bold')
        .fontSize(20)
        .fillColor(COLORS.white)
        .text(`Day ${day.day}  —  ${day.theme || ''}`, MARGIN, 38);

      doc
        .font('Helvetica-Bold')
        .fontSize(18)
        .fillColor(COLORS.primary)
        .text(day.day, PAGE_W - 70, 25);

      let dy = 95;

      // Day description
      if (day.description) {
        doc
          .font('Helvetica')
          .fontSize(10)
          .fillColor(COLORS.muted)
          .text(day.description, MARGIN, dy, { width: CONTENT_W });
        dy = doc.y + 14;
      }

      // Time slots
      const slots = [
        { label: '🌅 Morning', data: day.morning },
        { label: '☀️ Afternoon', data: day.afternoon },
        { label: '🌙 Evening', data: day.evening },
      ];

      slots.forEach((slot) => {
        if (!slot.data) return;
        if (dy > PAGE_H - 120) { doc.addPage({ margin: 0 }); dy = 60; }

        // Slot header
        rect(doc, MARGIN, dy, CONTENT_W, 1, COLORS.border);
        dy += 8;
        doc
          .font('Helvetica-Bold')
          .fontSize(11)
          .fillColor(COLORS.accent)
          .text(slot.label, MARGIN, dy);

        doc
          .font('Helvetica-Bold')
          .fontSize(12)
          .fillColor(COLORS.primary)
          .text(slot.data.activity || '', MARGIN, dy + 16, { width: CONTENT_W - 100 });

        // Duration & cost badge
        if (slot.data.duration || slot.data.cost) {
          const badge = [slot.data.duration, slot.data.cost].filter(Boolean).join('  ·  ');
          doc
            .font('Helvetica')
            .fontSize(8)
            .fillColor(COLORS.muted)
            .text(badge, MARGIN, dy + 16, { width: CONTENT_W, align: 'right' });
        }

        dy = doc.y + 4;

        if (slot.data.description) {
          doc
            .font('Helvetica')
            .fontSize(10)
            .fillColor('#444444')
            .text(slot.data.description, MARGIN, dy, { width: CONTENT_W, lineGap: 2 });
          dy = doc.y + 4;
        }

        if (slot.data.tips) {
          doc
            .font('Helvetica-Oblique')
            .fontSize(9)
            .fillColor(COLORS.muted)
            .text(`💡 ${slot.data.tips}`, MARGIN, dy, { width: CONTENT_W });
          dy = doc.y + 10;
        }
      });

      // Meals section
      if (day.meals && dy < PAGE_H - 150) {
        dy += 4;
        rect(doc, MARGIN, dy, CONTENT_W, 1, COLORS.border);
        dy += 10;

        doc
          .font('Helvetica-Bold')
          .fontSize(11)
          .fillColor(COLORS.accent)
          .text('🍽️ Where to Eat', MARGIN, dy);
        dy = doc.y + 8;

        const mealSlots = [
          { label: 'Breakfast', data: day.meals.breakfast },
          { label: 'Lunch', data: day.meals.lunch },
          { label: 'Dinner', data: day.meals.dinner },
        ];

        mealSlots.forEach((meal) => {
          if (!meal.data) return;
          doc
            .font('Helvetica-Bold')
            .fontSize(10)
            .fillColor(COLORS.primary)
            .text(`${meal.label}: `, MARGIN, dy, { continued: true })
            .font('Helvetica')
            .text(`${meal.data.name || ''}  ${meal.data.priceRange ? '(' + meal.data.priceRange + ')' : ''}`, { fillColor: '#444' });
          if (meal.data.description) {
            doc
              .font('Helvetica')
              .fontSize(9)
              .fillColor(COLORS.muted)
              .text(meal.data.description, MARGIN + 10, doc.y + 2, { width: CONTENT_W - 10 });
          }
          dy = doc.y + 6;
        });
      }

      // Daily budget footer bar
      if (day.dailyBudget) {
        const budgetY = PAGE_H - 60;
        rect(doc, 0, budgetY, PAGE_W, 60, COLORS.light);
        rect(doc, 0, budgetY, PAGE_W, 1, COLORS.border);

        const items = [
          { label: 'Activities', val: day.dailyBudget.activities },
          { label: 'Food', val: day.dailyBudget.food },
          { label: 'Transport', val: day.dailyBudget.transport },
          { label: 'Daily Total', val: day.dailyBudget.total },
        ];

        const colW = PAGE_W / items.length;
        items.forEach((item, i) => {
          const bx = i * colW + 20;
          const isTotal = i === items.length - 1;
          if (isTotal) rect(doc, i * colW, budgetY, colW, 60, COLORS.accent);
          doc
            .font('Helvetica')
            .fontSize(7)
            .fillColor(isTotal ? COLORS.primary : COLORS.muted)
            .text(item.label.toUpperCase(), bx, budgetY + 14);
          doc
            .font('Helvetica-Bold')
            .fontSize(11)
            .fillColor(isTotal ? COLORS.white : COLORS.primary)
            .text(item.val || '—', bx, budgetY + 28);
        });
      }
    });

    // ── Final Page — Thank You ────────────────────────────
    doc.addPage({ margin: 0 });
    rect(doc, 0, 0, PAGE_W, PAGE_H, COLORS.primary);
    rect(doc, 0, 0, PAGE_W, 6, COLORS.accent);

    doc
      .font('Helvetica-Bold')
      .fontSize(36)
      .fillColor(COLORS.white)
      .text('Safe Travels!', MARGIN, PAGE_H / 2 - 60, { width: CONTENT_W, align: 'center' });

    doc
      .font('Helvetica')
      .fontSize(13)
      .fillColor('#aaaacc')
      .text(
        'This itinerary was crafted by WanderLux AI.\nAlways verify opening hours and prices locally.',
        MARGIN,
        PAGE_H / 2 - 10,
        { width: CONTENT_W, align: 'center', lineGap: 6 }
      );

    doc
      .font('Helvetica-Bold')
      .fontSize(12)
      .fillColor(COLORS.accent)
      .text('wanderlux.ai', MARGIN, PAGE_H / 2 + 50, { width: CONTENT_W, align: 'center' });

    doc.end();
  });
}

module.exports = { generateItineraryPDF };
